2019-11-21 10:55:40,492 -  common.basepage -INFO - 等待元素 ('xpath', '//input[@name="phone"]') 可见。 - [basepage.py:24 ]
2019-11-21 10:55:40,525 -  common.basepage -INFO - 开始等待时间点：2019-11-21 10:55:40.493457，结束等待时间点：2019-11-21 10:55:40.524460，等待时长为：0:00:00.031003 - [basepage.py:32 ]
2019-11-21 10:55:40,525 -  common.basepage -INFO - 查找 输入手机号 中的元素 ('xpath', '//input[@name="phone"]')  - [basepage.py:64 ]
2019-11-21 10:55:40,532 -  common.basepage -INFO -  给元素 ('xpath', '//input[@name="phone"]') 输入文本内容:('17625188013',) - [basepage.py:122 ]
2019-11-21 10:55:40,702 -  common.basepage -INFO - 等待元素 ('xpath', '//input[@name="phoneCode"]') 可见。 - [basepage.py:24 ]
2019-11-21 10:55:40,727 -  common.basepage -INFO - 开始等待时间点：2019-11-21 10:55:40.702478，结束等待时间点：2019-11-21 10:55:40.727480，等待时长为：0:00:00.025002 - [basepage.py:32 ]
2019-11-21 10:55:40,727 -  common.basepage -INFO - 查找 输入验证码 中的元素 ('xpath', '//input[@name="phoneCode"]')  - [basepage.py:64 ]
2019-11-21 10:55:40,737 -  common.basepage -INFO -  给元素 ('xpath', '//input[@name="phoneCode"]') 输入文本内容:('sD2q',) - [basepage.py:122 ]
2019-11-21 10:55:40,791 -  common.basepage -INFO - 等待元素 ('xpath', '//a[@class="login"]') 可见。 - [basepage.py:24 ]
2019-11-21 10:55:40,816 -  common.basepage -INFO - 开始等待时间点：2019-11-21 10:55:40.791487，结束等待时间点：2019-11-21 10:55:40.816489，等待时长为：0:00:00.025002 - [basepage.py:32 ]
2019-11-21 10:55:40,816 -  common.basepage -INFO - 查找 登录 中的元素 ('xpath', '//a[@class="login"]')  - [basepage.py:64 ]
2019-11-21 10:55:40,824 -  common.basepage -INFO -  点击元素 ('xpath', '//a[@class="login"]') - [basepage.py:89 ]
2019-11-21 10:56:12,643 -  common.basepage -ERROR - 网页截屏失败！ - [basepage.py:186 ]
Traceback (most recent call last):
  File "D:\B2B\PageObjects\pc\index_page.py", line 19, in login_check
    self.driver.find_element_by_xpath('//a[contains(text(),"您不好")]')
  File "E:\Python3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "E:\Python3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "E:\Python3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "E:\Python3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(text(),"您不好")]"}
  (Session info: chrome=73.0.3683.103)
  (Driver info: chromedriver=2.36.540470 (e522d04694c7ebea4ba8821272dbef4f9b818c91),platform=Windows NT 6.1.7601 SP1 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\B2B\common\basepage.py", line 183, in save_web_screenshot
    self.driver.save_screenshot(screenshot_dir +"/" + filepath)
AttributeError: 'WebDriver' object has no attribute 'driver'
